<h2>Translations</h2>

<table>
    <thead>
        <tr>   
            <th>Language</th>
            <th>Done</th>
            <th>Translated</th>
            <th>Untranslated</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>German</td>
            <td>100%</td>
            <td>123</td>
            <td>456</td>
        </tr>
        <tr>
            <td>German</td>
            <td>100%</td>
            <td>123</td>
            <td>456</td>
        </tr>
        <tr>
            <td>German</td>
            <td>100%</td>
            <td>123</td>
            <td>456</td>
        </tr>
        <tr>
            <td>German</td>
            <td>100%</td>
            <td>123</td>
            <td>456</td>
        </tr>
        <tr>
            <td>German</td>
            <td>100%</td>
            <td>123</td>
            <td>456</td>
        </tr>
        <tr>
            <td>German</td>
            <td>100%</td>
            <td>123</td>
            <td>456</td>
        </tr>
        <tr>
            <td>German</td>
            <td>100%</td>
            <td>123</td>
            <td>456</td>
        </tr>
        <tr>
            <td>German</td>
            <td>100%</td>
            <td>123</td>
            <td>456</td>
        </tr>
    </tbody>
</table>